CREATE TABLE BOOK
(
    ID INTEGER NOT NULL
    , AUTHOR VARCHAR2(50) NOT NULL
    , NAME VARCHAR2(255) NOT NULL
    , PUBLICATION_DATE DATE NOT NULL
    , CONSTRAINT BOOK_PK PRIMARY KEY
    (
     ID
        )
    ENABLE
);
