CREATE TABLE AUTHOR
(
    ID INTEGER NOT NULL
    , SURNAME VARCHAR2(255) NOT NULL
    , NAME VARCHAR2(255) NOT NULL
    , MIDDLE_NAME VARCHAR2(255) NOT NULL
    , CONSTRAINT AUTHOR_PK PRIMARY KEY
    (
     ID
        )
    ENABLE
);


TRUNCATE TABLE BOOK;
ALTER TABLE BOOK ADD AUTHOR_ID INTEGER NOT NULL;
ALTER TABLE BOOK DROP COLUMN AUTHOR;
ALTER TABLE BOOK ADD CONSTRAINT FK_AUTHOR_BOOK foreign key (AUTHOR_ID) references AUTHOR;
