CREATE TABLE BOOK_ARCHIVE
(
    ID INTEGER NOT NULL
    , AUTHOR_ID INTEGER NOT NULL
    , NAME VARCHAR2(255) NOT NULL
    , PUBLICATION_DATE DATE NOT NULL
    , CONSTRAINT BOOK_ARCHIVE_PK PRIMARY KEY
    (
     ID
        )
    ENABLE
);

CREATE INDEX book_archive_title_i ON BOOK_ARCHIVE(title);