ALTER TABLE BOOK ADD DELETED VARCHAR(1);

UPDATE BOOK
    SET deleted = CASE WHEN (id in (SELECT id FROM BOOK_ARCHIVE)) THEN 'Y' ELSE 'N' END;

DROP TABLE BOOK_ARCHIVE;

CREATE INDEX book_del_i ON BOOK(deleted);