alter table AUTHOR modify (MIDDLE_NAME NULL);

CREATE TABLE PAGE
(
    ID INTEGER NOT NULL
    , PAGE INTEGER NOT NULL
    , PARSE_DATE DATE NOT NULL
    , CONSTRAINT PAGE_PK PRIMARY KEY
    (
     ID
        )
    ENABLE
);

CREATE SEQUENCE page_seq
    MINVALUE 1
    MAXVALUE 999999999999999999999999999
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
