# ===============================
# DEV PROFILE CONFIG
# ===============================

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-155-110-181.eu-west-1.compute.amazonaws.com:5432/ddjf3d1tbib3m7
    username: vngdikwmjlkvfy
    password: 1e809d84f5ddd7a97f26ffd0cbb7f73a3efcc87df15731f27f08b84028967ddf
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
    show-sql: true
  flyway:
    enabled: false
server:
  port: 5050


cas-login: https://localhost:8443/cas/login
cas-ticket-validate: https://localhost:8443/cas
cas-service: http://localhost:5050/login/cas